MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  modeltype: StrongerV3CDF
  backbone: 'mobilenetv2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
  boxloss: cdf
  l1scale: 0.1
  clsfocal: True
EXPER:
  experiment_name: 'strongerv3_cdf'
DATASET:
  dataset: 'VOC'

OPTIM:
  batch_size: 5
  lr_initial: 2e-4
  total_epoch: 60
  milestones: [10, 15]

Prune:
  sparse: False
